name: Download Godot-CPP source code


description: Download and extract the Godot-CPP source code for use in compiling


inputs:
  version:
    description: Version of Godot-CPP source code to download
    default: "4.4"


runs:
  using: "composite"

  steps:
      - name: Get Godot-CPP
        shell: sh
        run: |
          git -C godot-cpp config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git submodule sync --recursive godot-cpp
          git submodule
          git submodule update --init --recursive --remote godot-cpp
          cd godot-cpp/
          ls -l
          git checkout ${{ inputs.version }}