name: Download Godot-CPP source code


description: Download and extract the Godot-CPP source code for use in compiling


inputs:
  version:
    description: Version of Godot-CPP source code to download
    default: "4.4"


runs:
  using: "composite"

  steps:
      - name: Get Godot-CPP
        shell: sh
        run: |
          git submodule status
          git config -f .gitmodules submodule.godot-cpp.branch ${{ inputs.version }}
          git submodule update --init --recursive --remote godot-cpp
          git submodule status