on:
  workflow_call:
    inputs:
      godot_cpp_version:
        required: true
        type: number

      steamworks_sdk_tag:
        required: true
        type: string

    secrets:
      steamworks_sdk_repo:
        required: true

      steamworks_sdk_repo_token:
        required: true


jobs:
  build-windows:
    runs-on: windows-latest


    name: Windows ${{ matrix.name }}


    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 64-bit Templates
            cache-name: windows64
            arch: x86_64
            steam-redist: steam_api64.dll
            steam-redist-bin: win64/
            steam-redist-bits: 64

          - name: 32-bit Templates
            cache-name: windows32
            arch: x86_32
            steam-redist: steam_api.dll
            steam-redist-bin: ""
            steam-redist-bits: 32


    steps:
      - uses: actions/checkout@v4

      # Checkout GodotSteam
      - name: Checkout GodotSteam
        uses: actions/checkout@v4
        with:
          submodules: true

      # Download Godot-CPP to start
      - name: Download Godot-CPP
        uses: ./.github/actions/download-godot
        with:
          version: ${{ inputs.godot_cpp_version }}

      # Download Steamworks SDK
      - name: Download Steamworks SDK
        uses: ./.github/actions/download-steamworks
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      # Get that cache money
      - name: Setup Build Cache
        uses: ./.github/actions/setup-cache
        with:
          cache-name: ${{ matrix.cache-name }}
          godot-base: inputs.godot_cpp_version
        continue-on-error: true

      # Setup Python and SCONS
      - name: Setup Python and SCONS
        uses: ./.github/actions/setup-dependencies

      # Compiling templates
      - name: ${{ matrix.steam-redist-bits }}-bit Debug Template Compilation (target=template_debug)
        uses: ./.github/actions/build-godot
        with:
          arch: ${{ matrix.arch }}
          platform: windows
          target: template_debug

      - name: Upload ${{ matrix.steam-redist-bits }}-bit Debug Template
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-debug-template
          path: ./bin/libgodotsteam.windows.template_debug.${{ matrix.arch }}.dll

      - name: ${{ matrix.steam-redist-bits }}-bit Release Template Compilation (target=template_release)
        uses: ./.github/actions/build-godot
        with:
          arch: ${{ matrix.arch }}
          platform: windows
          target: template_release

      - name: Upload ${{ matrix.steam-redist-bits }}-bit Release Template
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-release-template
          path: ./bin/libgodotsteam.windows.template_release.${{ matrix.arch }}.dll

      - name: Clear bin
        shell: bash
        run: |
          rm -rf bin

      # Upload the Steam redistributable for packaging
      - name: Upload Windows Steam File
        uses: ./.github/actions/upload-steam-redistributable
        with:
          name: windows${{ matrix.steam-redist-bits }}-steam
          path: ${{ matrix.steam-redist-bin }}
          redist: ${{ matrix.steam-redist }}
